[server]
port=8501 # change port number. By default streamlit uses 8501 port
headless=true # This will eliminate automatically open browser

[browser] # This ip and port will show in command prompt
 # Put your Local IP or Domain Name
serverPort = 8501

[theme]

# Primary accent for interactive elements
primaryColor = '#000000'

# Background color for the main content area
backgroundColor = '#ffffff'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#0963AF'

# Color used for almost all text
textColor = '#000000' 

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "serif"


